import type { MetadataRoute } from 'next';

/**
 * Web app manifest (served by Next at /manifest.webmanifest).
 *
 * `id` and `start_url` are both `/` so the installed app launches straight into
 * the reader. Icons are generated by scripts/make-icons.py.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'RSS Reader',
    short_name: 'RSS',
    description: 'A single-user RSS reader with in-app full-text reading.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'any',
    // Matches the sepia theme (the app default) so the splash screen and the
    // status bar do not flash a colour the app never uses.
    background_color: '#f2e9d8',
    theme_color: '#f2e9d8',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
